name: Test Pipeline

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23 

      - name: Build Docker Image
        run: docker build -t schedlink:${{ github.sha }} .

      - name: Run go test
        run: go test ./... -v

      - name: Run go build
        run: go build ./cmd/server


      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.63.4
